services:
  postgres:
    image: 'postgres:14.6'
    environment:
      - 'POSTGRES_DB=spring_modulith'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - /c/tmp/postgres_modulith:/var/lib/postgresql/data